spring.application.name=anki_copy

spring.datasource.url=jdbc:postgresql://<HOST>:5432/<DBNAME>
spring.datasource.username=<USER>
spring.datasource.password=<PASSWORD>
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
